routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');
Route::resource('/vacations','VacationsController');
Route::get('/create','VacationsController@create')->name('create');
Route::post('/vacations/store','VacationsController@store')->name('vacations.store');
//Route::post('/vacations/update','VacationsController@update')->name('vacations.update');
Route::get('/unauthorized',function (){
    return "Unauthorized request";
});
Route::post('/comment/{vacation}','CommentController@store')->name('comments.store');
Route::get('/test/env', function () {
    dd(env('DB_DATABASE')); // dump db variable value one by one
});

Route::get('employee/vacation','HomeController@employeeVacations')->name('employeeVacations');
Route::get('manager/vacation','HomeController@managerVacations')->name('allVacations');

//Route::resource('/user','UserController');

Route::get('/profile','UserController@show')->name('user.show');
//SQL injection
Route::put('profile/profile/{user}','UserController@update')->name('user.update');

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
    <style>
        {{--@media (max-width: 760px) {--}}
        {{--    .jumbotron {--}}
        {{--        background-image: url("{{URL::asset('img/HR_BG.jpg')}}");--}}
        {{--        background-size: 100%;--}}
        {{--        height: 600px;--}}
        {{--        /*background-size: cover;*/--}}
        {{--        background-repeat: no-repeat;--}}
        {{--        position: relative;--}}
        {{--        background-position: center;--}}
        {{--    }--}}

        {{--}--}}
        .jumbotron {
            background-image: url("{{URL::asset('img/HR_BG.jpg')}}");
            background-size: 100%;
            height: 600px;
            /*background-size: cover;*/
            background-repeat: no-repeat;
            position: relative;
            background-position: center;
        }

        .img-text {
            position: absolute;
            border-radius: 40px;
            bottom: 0px;
            width: 95%;
            padding-top: 5px;
            /* height: 50px; */
            margin-top: 40px;
            color: #1965b6;
            text-align: center;
            font-size: 30px;
            background-color: #eaf3fae0;
        }
    </style>



    @if($user_role!='Manager')

        <div class="jumbotron ">
            <div class="img-text">
                <h3> {{__('Welcome to HR system')}}</h3>
                <p class="lead">{{__('By using HR system you can keep track of your requests easily anytime anywhere')}}</p>
                <a href="{{route('vacations.create')}}" class="btn btn-sm btn-primary mb-4">{{__('New Request')}}</a>
                <a href="{{route('employeeVacations')}}"
                   class="btn btn-sm btn-secondary mb-4">{{__('Your requests')}}</a>
            </div>
        </div>
    @endif
    <div>
        @if($user_role=='Manager')

            <div class="jumbotron">
                <div class="img-text">
                    <h3>{{__('Welcome to HR system')}}</h3>
                    <p class="lead">{{__('By using HR system you can manage your organization anytime anywhere')}}</p>
                    <a href="{{route('allVacations')}}" class="btn btn-sm btn-primary mb-4">{{__('All Requests')}}</a>

                </div>
            </div>
        @endif
    </div>
    <script>
        // let vacations = document.getElementById('vacations');
        // let statuses = document.getElementsByClassName('status');
        // for(let s of statuses){
        //     if(s.innerHTML === 'pending'){
        //         s.classList.remove('badge-danger')
        //         s.classList.add('badge-primary')
        //     }
        // }
        // for(let status in statuses){
        //     console.log(status.innerHTML)
        // }
        // console.log(vacations, status)
        // alertify.confirm("This is a confirm dialog.",
        //     function(){
        //         alertify.success('Ok');
        //     },
        //     function(){
        //         alertify.error('Cancel');
        //     });
        {{--let status = {!! json_encode($vacation->status,JSON_HEX_TAG) !!};--}}

        {{--if(status=='pending'){--}}
        {{--    document.getElementById('badge').className='badge badge-info';--}}

        {{--}--}}
        {{--if(status=='approved'){--}}
        {{--    document.getElementById('badge').className='badge badge-success';--}}
        {{--}--}}

        {{--if(status=='rejected'){--}}
        {{--    document.getElementById('badge').className='badge badge-danger';--}}
        {{--}--}}
        {{--    if ({!! json_encode(Auth::user()->role != 'Manager')!!}) {--}}
        {{--        let btn_edit = document.getElementById('edit_btn');--}}
        {{--         btn_edit.style.display = "none";--}}
        {{--    }--}}


    </script>

@endsection

resources/views/profile.blade.php
@extends('layouts.app')
@section('content')
    <style>
        .card {
            margin: 0 auto;
            float: none;
            margin-bottom: 10px;
        }
    </style>

    <div class="card col-6">
        <div class=" m-3 " style="font-size: 44px; text-align:center;">
            <i class="fa fa-user-circle-o fa-5x" style="color:lightgray;"></i>
        </div>
        <form action={{route('user.update',$user)}} method="post">
            @csrf
            @method('PUT')
            <div class="form-group p-3">
                <label class="font-weight-bolder mt-2 " for='name'>{{__('Name')}}</label>
                <input class="form-control pt-2" name="name" id="name" type="text" value="{{$user->name}}">

                <label class="font-weight-bold mt-2" for='email'>{{__('E-Mail Address')}}</label>
                <input class="form-control " name="email" id="email" type="email" value="{{$user->email}}">

                <label class="font-weight-bold mt-2" for='job_title'>{{__('Job Title')}}</label>
                <input class="form-control" name="job_title" id="job_title" type="text"
                       value="{{$user->job_title}}">

                <label class="font-weight-bold mt-2" for='DoB'>{{__('Date of Birth')}}</label>
                <input class="form-control" name="DoB" id="DoB" type="date" value="{{$user->DoB}}">

            </div>
            <div class="form-group p-3">
                <input class="form-control btn btn-outline-success bt-lg" type="submit" name="submit"
                       value="{{__('Save')}}"/>
            </div>
        </form>

    </div>

@endsection