routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');
Route::resource('/vacations','VacationsController');
Route::get('/create','VacationsController@create')->name('create');
Route::post('/vacations/store','VacationsController@store')->name('vacations.store');
//Route::post('/vacations/update','VacationsController@update')->name('vacations.update');
Route::get('/unauthorized',function (){
    return "Unauthorized request";
});
Route::post('/comment/{vacation}','CommentController@store')->name('comments.store');
Route::get('/test/env', function () {
    dd(env('DB_DATABASE')); // dump db variable value one by one
});

Route::get('employee/vacation','HomeController@employeeVacations')->name('employeeVacations');
Route::get('manager/vacation','HomeController@managerVacations')->name('allVacations');

//Route::resource('/user','UserController');

Route::get('/profile','UserController@show')->name('user.show');
//SQL injection
Route::put('profile/profile/{user}','UserController@update')->name('user.update');

app/Vacation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vacation extends Model
{
    protected $fillable = [
        'title',
        'type',
        'start_date',
        'end_date',
        'description',
        'attachment',
        'user_id',
        'status'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

}

app/Http/Controllers/VacationsController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Vacation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class VacationsController extends Controller
{
    public function __construct()
    {
        //   $this->middleware('auth');
        $this->middleware('checkRole')->only('edit', 'update');
    }

    public function create()
    {
        //$vacationTypes = ['annual' => 'annual', 'sick' => 'sick', 'exceptional' => 'exceptional'];
        //compact($vacationTypes)
        return View('vacations.create' );
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        $request->validate([
            'title' => 'required|max:50',
            'type' => 'required',
            'description' => 'required|min:30',
            'start_date' => 'required',
            'end_date' => 'required',
            'attachment' => 'mimes:pdf,xlx,csv|max:2048',

        ]);
        if (request()->hasFile($request['attachment'])) {
            $fileName = time() . '.' . $request->attachment->extension();
            $request->attachment->move(public_path('uploads'), $fileName);
            $vacation = ['title' => $request['title'],
                'type' => $request['type'],
                'description' => $request['description'],
                'attachment' => $fileName,
                'start_date' => $request['start_date'],
                'end_date' => $request['end_date']
            ];
            $user->vacations()->create($vacation);
        } else $user->vacations()->create($request->all());

        //route
        return redirect()->to('employee/vacation');
    }

//    public function fileUploadPost(Request $request)
//    {
////        $request->validate([
////            'file' => 'required|mimes:pdf,xlx,csv|max:2048',
////        ]);
//
//        $fileName = time().'.'.$request->file->extension();
//
//        $request->file->move(public_path('uploads'), $fileName);
//
//        return back()
//            ->with('success','You have successfully upload file.')
//            ->with('file',$fileName);
//
//    }

    /**
     * Display the specified resource.
     *
     * @param \App\Vacation $vacation
     * @return \Illuminate\Http\Response
     */
    public function edit(Vacation $vacation)
    {

        return View('vacations.edit', compact('vacation'));

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Vacation $vacation
     * @return \Illuminate\Http\Response
     */
    public function show(Vacation $vacation)
    {
        $user_role = Auth::user()->role;
        return View('vacations.show', compact('vacation', 'user_role'));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Vacation $vacation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vacation $vacation)
    {
        if (Auth::id() != $vacation->user_id) {
            return abort(401);
        }
        $vacation->delete();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Vacation $vacation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vacation $vacation)
    {
        $vacation->update($request->all());
        return redirect()->back();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

}

resources/views/vacations/create.blade.php
@extends('layouts.app')
@section('title',__('New Vacation'))
@section('content')
   <h2>{{__('Request New Vacation')}}</h2>
   <form action="{{route('vacations.store')}}" method="post" enctype="multipart/form-data">
       @csrf
       <div class="form-group">
           <label for="title">{{__('Title')}}</label>
           <input class="form-control col-6" type="text" name="title">
       </div>
       <div class="form-group">
           <div>
               <label>{{__('Request category')}}</label>
           </div>

           <input type="radio" id="type1" name="type" value="0">
           <label for="type1"> {{__('Annual')}}</label>
           <input type="radio" id="type3" name="type" value="1">
           <label for="type3"> {{__('Sick')}}</label>
           <input type="radio" id="type4" name="type" value="2">
           <label for="type4"> {{__('Exceptional')}}</label>


       </div>
       <div class="form-group">
           <label for="start_date">{{__('Start Date')}}</label>
           <input type="date" class="form-control col-6"  id="start_date" name="start_date">
           <label for="end_date">{{__('End Date')}}</label>
           <input class="form-control col-6" type="date" id="start_date" name="end_date">
       </div>

       <div class="form-group ">
           <label for="description">{{__('Description')}}</label>
           <textarea name="description" id="description" rows="10" cols="30" class="form-control col-6"></textarea>
       </div>

       <div class="form-group">
           <label for="attachment">{{__('Select a file (optional)')}}</label>
           <input class="form-control col-6" type="file" id="attachment" name="attachment">
       </div>
       <div class="form-group">
           <button class="form-control btn btn-success col-6" type="submit">{{__('Send')}}</button>
       </div>

   </form>
    @endsection

resources/views/vacations/edit.blade.php
@extends('layouts.app')
@section('title',__('New Vacation'))
@section('content')
    <h2>{{__('Edit Vacation\'s Status')}}</h2>
    <form action="{{route('vacations.update',$vacation)}}" method="post">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="title">{{__('Title')}}</label>
            <input class="form-control col-6" type="text" name="title" @isset($vacation) disabled value="{{__($vacation->title)}}" @endisset>
        </div>
        <div class="form-group">
            <div>
                <label>{{__('Request category')}}</label>
            </div>

            <input type="radio" id="type1" name="type" value="{{__('Annual')}}"  @isset($vacation) disabled checked @endisset">
            <label for="type1"> {{__('Annual')}}</label>
            <input type="radio" id="type3" name="type" value="{{__('Sick')}}" @isset($vacation) disabled checked @endisset">
            <label for="type3"> {{__('Sick')}}</label>
            <input type="radio" id="type4" name="type" value="{{__('Exceptional')}}" @isset($vacation) disabled checked @endisset">
            <label for="type4"> {{__('exceptional')}}</label>
        </div>
        <div class="form-group">
            <label for="start_date">{{__('Start Date')}}</label>
            <input type="date" class="form-control col-6"  id="start_date" name="start_date"  @isset($vacation) disabled value="{{__($vacation->start_date)}}" @endisset>
            <label for="end_date">{{__('End Date')}}</label>
            <input class="form-control col-6" type="date" id="end_date" name="end_date" @isset($vacation) disabled value="{{__($vacation->end_date)}}" @endisset>
        </div>

        <div class="form-group ">
            <label for="description">{{__('Description')}}</label>
            <textarea name="description" id="description" rows="10" cols="30" class="form-control col-6" @isset($vacation) disabled @endisset>@isset($vacation) {{__($vacation->description)}} @endisset</textarea>
        </div>
{{--        <div class="form-group">--}}
{{--            <label for="attachment">{{__('Select a file (optional)')}}</label>--}}
{{--            <input class="form-control col-6" type="file" id="attachment" name="attachment">--}}
{{--        </div>--}}
        <div class="form-group">
            <select class=" form-control col-6" name="status" id="status">
                <option value="pending">{{__('Pend')}}</option>
                <option value="approved">{{__('Approve')}}</option>
                <option value="rejected">{{__('Reject')}}</option>
            </select>
        </div>
        <div class="form-group">
            <button class="form-control btn btn-success col-6" type="submit">{{__('Edit')}}</button>
        </div>

    </form>
@endsection

resources/views/vacations/employee_vacations.blade.php
@extends('layouts/app')
<style>
    .badge {
        position: absolute;
        top: 10px;
        left: 0;
        margin-left: 5px;
        width: auto;
    }

</style>
@section('content')

    @if($user_role!='Manager')
            <div>
                <a href="{{route('vacations.create')}}" class="btn btn-sm btn-primary mb-4">{{__('New Request')}} <i class="fa fa-plus"></i></a>

                <h4>{{__('Your requests')}}</h4>
            </div>
        <div class="row" id="vacations">
    @forelse($vacations as $vacation)
        <div class="col-md-3">
            <div class="card mb-2">
                <div class="card-body">
                    <a href="{{route('vacations.show',$vacation)}}"> {{$vacation->title}}</a>
                    <span id="badge" class="status badge
@if($vacation->status === 'pending'|$vacation->status === 'معلق')
                        badge-info
                        @elseif($vacation->status === 'approved'|$vacation->status === 'مقبول')
                    badge-success
                    @elseif($vacation->status ==='rejected' |$vacation->status === 'مرفوض')
                        badge-danger
@endif
">{{__($vacation->status)}}</span>
                </div>
                <div class="card-footer ">
                    <form method="post" action="{{route('vacations.destroy',$vacation)}}"
                          style="">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-outline-danger btn-sm col-12" id="btn-delete"
                                onclick="return confirm('{{__('Are you sure?')}}')">{{__('Delete')}} <i class="fa fa-trash"></i></button>
                    </form>
                </div>
            </div>
        </div>
            @empty
        <p>{{ __('You don\'t have any requests yet') }}</p>
    @endforelse
        </div></div>


            @endif
@endsection

resources/views/vacations/managerView.blade.php
@extends('layouts.app')
@section('content')
    <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/rowreorder/1.2.7/css/rowReorder.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.dataTables.min.css" rel="stylesheet">

    <div>
        <h4 class="text-info p-3"><b>{{__('Employee\'s requests')}}</b></h4>
    </div>
    <table class="table table-hover" id="myTable">
        <thead>
        <tr class="table-info">
            <th>{{__('Title')}}</th>
            <th>{{__('Status')}}</th>
            <th>{{__('Type')}}</th>
            <th>{{__('From')}}/{{__('to')}}</th>
            <th>{{__('Employee')}}</th>
            <th>{{__('File')}}</th>
            <th></th>
            {{--        <th>{{__('Edit the status')}}</th>--}}
        </tr>
        </thead>
        @forelse($vacations as $vacation)
            <tr>
                <th> {{$vacation->title}}</a> </th>
                <th class="@if($vacation->status==='approved')text-success
                        @elseif($vacation->status==='rejected')text-danger
                          @elseif($vacation->status==='pending')text-info
                        @endif"> {{__($vacation->status)}}</th>
                <th>{{__($vacation->type)}}</th>
                <th>{{__('From')}} : {{$vacation->start_date}} {{__('to')}} : {{$vacation->end_date}} </th>
                <th> {{$vacation->user->name}}</th>
                <th>  @isset($vacation->attachment)<a
                        href='{{ asset("uploads/$vacation->attachment") }}' target="_blank">{{$vacation->attachment}} </a>@endisset
                </th>
                <th><a href="{{route('vacations.show',$vacation)}}"
                       class="btn btn-outline-info btn-sm" id="edit_btn"> <i class="fa fa-info" aria-hidden="true"></i></a>
                </th>

            </tr>


        @empty
            {{__('No requests yet')}}
        @endforelse
    </table>


@endsection
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>

<script>
    $(document).ready(function () {
        $.noConflict();
        $('#myTable').DataTable({
            "serverSide": false,
            'sort': true,
            "processing": false,
            "searching": false,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Arabic.json"
            },
            rowReorder: {
                selector: 'td:nth-child(2)'
            },
            responsive: true

        });

    });

</script>

resources/views/vacations/show.blade.php
@extends('layouts.app')
@section('title',$vacation->title)
@section('content')
    <style>

    </style>
    <div class="card">
        <h3 class="card-header alert-info">
            {{$vacation->title}}
        </h3>
        <div class="card-body">
            <p><b>{{__('Description')}} </b></p>
            <p>{!! nl2br($vacation->description) !!}</p>
            <p><b>{{__('Request category')}}:</b> {!! __(nl2br($vacation->type))!!}</p>
            <p><b>{{__('From')}}:</b> {!! nl2br($vacation->start_date) !!} <b>{{__('to')}}
                    :</b> {!! nl2br($vacation->end_date) !!}</p>
            <p id="status"><b>{{__('Request status')}}:</b> {!! nl2br(__($vacation->status)) !!}</p>
            <p>@isset($vacation->attachment) {{__('Attachment')}} : <a
                    href='{{ asset("uploads/$vacation->attachment")}}' target="_blank">{{$vacation->attachment}}</a>@endisset</p>

            @if($user_role=='Manager')
                <a id="edit" class="text-link" style="color: #ed7d2a" >{{__('Edit')}} <i
                        class="fa fa-pencil"></i></a>
                <div id="edit-form" style="display: none">
                    <form action="{{route('vacations.update',$vacation)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group p-3">
                            <select class=" form-control col-4 pt-1 pb-1" name="status" id="status">
                                <option value="pending">{{__('Pend')}}</option>
                                <option value="approved">{{__('Approve')}}</option>
                                <option value="rejected">{{__('Reject')}}</option>
                            </select>

                            <button id="btn-edit" type="submit" class="btn btn-success text-light m-3"> {{__('Edit')}}
                                <i class="fa fa-pencil"></i></button>
                        </div>
                    </form>
                </div>
            @endif
            {{--             here will be a link to open attachments--}}
        </div>
        <div class="dropdown-divider mt-3 "></div>
        <div class="article-footer  ml-3 mb-3">
            <div><b>{{__('Employee')}}:</b> {{$vacation->user->name}}</div>
            <div><b>{{__('Created at')}}:</b> {{$vacation->created_at}}</div>
            <div><b>{{__('Updated at')}}:</b> {{$vacation->updated_at}}</div>
        </div>


    </div>

    <div id="comments" class="mt-4">
        <h5 class="card-header alert-info">{{__('Comments')}}</h5>

        @forelse($vacation->comments as $comment)
            <div class="card p-3 mt-2">
                {{$comment->content}}
                <div class="dropdown-divider mt-3"></div>
                <p>{{__('Author')}}:{{$comment->user->name}}</p>


            </div>
        @empty

            {{__('No comments yet')}}
        @endforelse
    </div>
    @auth
        <div id="comment-form " class="mt-5">
            <div class="card">
                <h5 class="card-header alert-secondary">{{__('Type your comment here')}}</h5>
                <div class="card-body">
                    <form action="{{route('comments.store',$vacation->id)}}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="content">{{__('Content')}}</label>
                            <textarea
                                class="form-control"
                                placeholder="{{__('Type your comment here')}}"
                                name="content"
                                id="content"
                                cols="30"
                                rows="10"></textarea>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success" type="submit">{{__('Save')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @else
        <p class="text-secondary mt-3"><a href="{{route('login')}}">{{__('Login to post a comments')}}</a></p>
    @endauth
@endsection
<script src="/JS/jquery-3.5.1.js"></script>
<script>
  //  use jQuery and toggle to do this
  //
  //   function showForm() {
  //       var x = document.getElementById("edit-form");
  //       if (x.style.display === "none") {
  //           x.style.display = "block";
  //       } else {
  //           x.style.display = "none";
  //       }
  //   }
        $(document).ready(function () {
            $('#edit').click(function () {
                $('#edit-form').toggle();
            });
        });

</script>